### ISSUE TITLE
`/proc/xxx/stat`: No such file or directory

### ISSUE THREAD

**Issue by eroux** [France-ioi/taskgrader#6]
Salut !

J'essaye le taskgrader avec le script `genJson.py` dans le repo des exos France-IOI, mais j'obtiens une erreur:

```
$ ./_common/genJson/genJson.py FranceIOI/Contests/2015/Algorea_demi_finale/guitar_hero/
* Generating defaultParams for FranceIOI/Contests/2015/Algorea_demi_finale/guitar_hero/
gen.sh detected
Dependencies found for generator: gen.sh, generators.py, libRobot.py, gen-simon-glouton.cpp, gen-isma-randby5.cpp, gen-isma-random.cpp, sol-isma-ref.cpp, gen-simon-gloutonparcouche.cpp
No sanitizer detected
check.cpp detected

* Output from auto-test with taskgrader
open(/proc/20599/stat): No such file or directory
Traceback (most recent call last):
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 790, in <module>
    json.dump(evaluation(inJson), sys.stdout)
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 644, in evaluation
    getCacheDir(generatorsFiles[gen['idGenerator']], 'e-generator'), outputFiles=['*.in', '*.out', '*.h', '*.java', '*.ml', '*.mli', '*.pas', '*.py'])
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 399, in cachedExecute
    report = execute(executionParams, cmdLine, workingDir, stdinFile=stdinFile, stdoutFile=stdoutFile, language=language)
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 313, in execute
    filecopy(isolateDir + 'isolated.stdout', stdoutFile)
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 84, in filecopy
    shutil.copy(filefrom, fileto)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 13] Permission denied: '/tmp/box/75/box/isolated.stdout'


*** /!\ Some tasks returned errors:
FranceIOI/Contests/2015/Algorea_demi_finale/guitar_hero/
```

est-ce que tu sais d'où ça peut venir ?

**Comment by eroux** [comment]
Juste pour info, j'ai checké mon kernel, il a bien toutes les options nécessaires pour faire tourner isolate

**Comment by eroux** [comment]
Aussi, ça c'était avec `CFG_CONTROLGROUPS` à `False`, à `True` ça donne:

```
Cannot write /sys/fs/cgroup/memory/box-48/tasks: No such file or directory
Traceback (most recent call last):
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 790, in <module>
    json.dump(evaluation(inJson), sys.stdout)
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 644, in evaluation
    getCacheDir(generatorsFiles[gen['idGenerator']], 'e-generator'), outputFiles=['*.in', '*.out', '*.h', '*.java', '*.ml', '*.mli', '*.pas', '*.py'])
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 399, in cachedExecute
    report = execute(executionParams, cmdLine, workingDir, stdinFile=stdinFile, stdoutFile=stdoutFile, language=language)
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 313, in execute
    filecopy(isolateDir + 'isolated.stdout', stdoutFile)
  File "/home/eroux/repos/taskgrader/taskgrader.py", line 84, in filecopy
    shutil.copy(filefrom, fileto)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 13] Permission denied: '/tmp/box/48/box/isolated.stdout'
```

**Comment by eroux** [comment]
fixed by bf6a56925a68c45f22721822b0f05a36f8660883
